application:
  title: Twitter Trends
  version: 1.0.0

twitter-tokens:
  consumerKey:
  consumerSecret:
  token:
  secret:

twitter:
  search-terms: kafka, java, springboot
  queue-size: 1000

kafka:
  bootstrap.server: 127.0.0.1:9092
  schema.registry.url: http://127.0.0.1:8081
  topic: filtered_tweets

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.apache.kafka: INFO
    com.vish.tweet: DEBUG
  file:
    path: producer
    name: log/producer.log
    max-size: 5MB
  pattern:
    rolling-file-name: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
    file: "%d{yyyy-MM-dd HH:mm:ssZ} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%15.15t] %-40.40logger{39} : %m%n"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSSZ}){faint} %clr(${LOG_LEVEL_PATTERN:%5p})\
              {magenta} %clr(-){faint}%clr([%5.5t]){faint}%clr(%-30.30logger{30}){cyan} %clr(:){faint} %m%n"

# configs for actuator endpoints
management:
  server.port: 8080
  endpoint:
    info.cache.time-to-live: 5s
    health:
      show-details: always
      cache.time-to-live: 5s
    metrics.enabled: true
    prometheus:
      enabled: true
  endpoints:
    web.exposure.include: "*"
    base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
        step: 30s